/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e99eb2782f82d390e776d41
*
* You will get 10% discount for each one of your friends
* 
*/
// START - USED SERVICES
/*
 *	aziendeService.create
 *		PARAMS: 
 *		
 *
 *	aziendeService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 *	aziendeService.get
 *		PARAMS: 
 *					ObjectId id - Id resource
 *		
 *
 *	contattiService.findBycognome
 *		PARAMS: 
 *					Objectid key - Id of model to search for
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * aziendeService  
 * contattiService  
 */
// END - REQUIRED RESOURCES

app.controller('aziendeEditController', ['$scope', '$location', '$routeParams', '$q', 'aziendeService', 'contattiService', 'contattiService',
    function ($scope, $location, $routeParams, $q, aziendeService , contattiService , contattiService) {

    	//manage create and save
		$scope.external = {};
		
    	if ($routeParams.id != 'new')
    	{
        	$scope.id = $routeParams.id;
        	$scope.obj = aziendeService.get({_id: $scope.id});
        	$scope.external._contatticognome = contattiService.findBycognome({key: $scope.id});
        	
    	}
    	else{
    		$scope.obj = new aziendeService();
        	$scope.external._contatticognome = [];
        	
    	}
    	
    	$scope.save = function(){
    		$scope.obj.$save().then(function(data){
    			$scope.obj=data;
        		$location.path('/aziendes/');
    		});
    	}
    	
    	$scope.remove = function(){
    		aziendeService.remove({_id: $scope.obj._id}).$promise.then(function(){
				$('#removeModal').modal('hide');
				$('.modal-backdrop').remove();
				$('.modal-open').removeClass("modal-open");
        		$location.path('/aziendes/');
    		});
    	}
    	
    		
        //manage External relation cognome
        		
    	$scope.list_contatticognome = contattiService.query();
    	
}]);