/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e99eb2782f82d390e776d41
*
* You will get 10% discount for each one of your friends
* 
*/
// START - USED SERVICES
/*
 *	contattiService.create
 *		PARAMS: 
 *		
 *
 *	contattiService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 *	contattiService.get
 *		PARAMS: 
 *					ObjectId id - Id resource
 *		
 *
 *	aziendeService.list
 *		PARAMS: 
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * aziendeService  
 * contattiService  
 */
// END - REQUIRED RESOURCES

app.controller('contattiEditController', ['$scope', '$location', '$routeParams', '$q', 'aziendeService', 'contattiService', 'aziendeService',
    function ($scope, $location, $routeParams, $q, aziendeService , contattiService , aziendeService) {

    	//manage create and save
		$scope.external = {};
		
    	if ($routeParams.id != 'new')
    	{
        	$scope.id = $routeParams.id;
        	$scope.obj = contattiService.get({_id: $scope.id});
        	
    	}
    	else{
    		$scope.obj = new contattiService();
        	
    	}
    	
    	$scope.save = function(){
    		$scope.obj.$save().then(function(data){
    			$scope.obj=data;
        		$location.path('/contattis/');
    		});
    	}
    	
    	$scope.remove = function(){
    		contattiService.remove({_id: $scope.obj._id}).$promise.then(function(){
				$('#removeModal').modal('hide');
				$('.modal-backdrop').remove();
				$('.modal-open').removeClass("modal-open");
        		$location.path('/contattis/');
    		});
    	}
    	
    		
        //manage relation cognome
        		
    	$scope.list_aziende = aziendeService.query();

    	$scope.contain_aziende = function(item){
    		if (!$scope.obj.cognome) return false;
    		return $scope.obj.cognome.indexOf(item) != -1;
    	}
		    	
		$scope.add_aziende = function(item){
			if(!$scope.obj.cognome)
				$scope.obj.cognome = [];
			$scope.obj.cognome.push(item);
		}
		
		$scope.remove_aziende = function(index){
			$scope.obj.cognome.splice(index, 1);
		}
}]);